version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  php:
    image: rgeffroy/symfony
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./workspace:/srv
  nginx:
    image: nginx:stable
    depends_on:
      - php
    volumes:
      - ./workspace:/srv
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
  sftp:
    image: emberstack/sftp
    volumes:
      - ./workspace:/home/foo
      - ./docker/sftp/sftp.json:/app/config/sftp.json:ro
    ports:
      - "2200:22"
